const MANUAL=window.APP_DATA,LEARN=window.LEARN_DATA,FIGHTS=window.FIGHT_DATA,GUIDED=window.GUIDED_DATA,main=document.getElementById('main');
let deferredInstall=null,waitingWorker=null;
const PROGRESS_KEY='snd-lesson-progress-v330',MISSION_KEY='snd-active-mission-v330',HISTORY_KEY='snd-mission-history-v330',NOTES_KEY='snd-beginner-notes';
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const saveJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const toast=msg=>{const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display='none',1900)};
const terms=[...LEARN.terms];
(MANUAL.dictionary||[]).forEach(d=>{const id=slug(d.term);if(!terms.some(t=>t.id===id))terms.push({id,term:d.term,definition:d.definition})});
const termById=id=>terms.find(t=>t.id===decodeURIComponent(id))||terms.find(t=>slug(t.term)===decodeURIComponent(id));
const quickById=id=>LEARN.quick.find(x=>x.id===id),lessonById=id=>LEARN.lessons.find(x=>x.id===id),fightById=id=>FIGHTS.find(x=>x.id===id),missionById=id=>GUIDED.missions.find(x=>x.id===id);
function go(path){location.hash='#/'+path}
function route(){return location.hash.replace(/^#\/?/,'')||'home'}
function setNav(root){const mapped=['lesson','fights','fight','manual','operation'].includes(root)?'learn':root==='notes'?'practice':root;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.root===mapped))}
function shareButton(){return `<button class="sharebtn" data-share>Copy page link</button>`}
function bindShare(){const b=document.querySelector('[data-share]');if(b)b.onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Page link copied')}catch{prompt('Copy this link:',location.href)}}}
function bindGo(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function termNote(ids=[]){const found=[...new Set(ids)].map(termById).filter(Boolean);if(!found.length)return'';return `<div class="term-note"><p><strong>Game terms on this page.</strong> Tap a term for its dictionary definition.</p><div class="term-chips">${found.map(t=>`<a class="term-chip" href="#/term/${encodeURIComponent(t.id)}">${esc(t.term)}</a>`).join('')}</div></div>`}
function termsInText(text=''){const s=text.toLowerCase();return terms.filter(t=>s.includes(t.term.toLowerCase())).slice(0,7).map(t=>t.id)}
function progress(){const p=readJSON(PROGRESS_KEY,{completed:[],last:null});p.completed=Array.isArray(p.completed)?p.completed:[];return p}
function setLastLesson(id){const p=progress();p.last=id;saveJSON(PROGRESS_KEY,p)}
function toggleLesson(id){const p=progress();p.completed=p.completed.includes(id)?p.completed.filter(x=>x!==id):[...p.completed,id];p.last=id;saveJSON(PROGRESS_KEY,p);renderLesson(id);toast(p.completed.includes(id)?'Lesson marked complete':'Lesson marked incomplete')}
function activeMission(){return readJSON(MISSION_KEY,null)}
function missionHistory(){return readJSON(HISTORY_KEY,[])}
function startMission(mission,source='Guide'){const m={id:mission.id,title:mission.title,short:mission.short||'',instruction:mission.instruction,cue:mission.cue||'',route:mission.route||'',source,rounds:0,successes:0,results:[],startedAt:new Date().toISOString()};saveJSON(MISSION_KEY,m);go('practice');toast('Practice mission started')}
function startMissionById(id,source='Guided diagnosis'){const m=missionById(id);if(m)startMission(m,source)}
function recordMission(ok){const m=activeMission();if(!m||m.rounds>=5)return;m.rounds++;if(ok)m.successes++;m.results.push(ok?'yes':'no');saveJSON(MISSION_KEY,m);renderPractice();if(m.rounds===5)toast(`Five rounds complete: ${m.successes}/5`)}
function finishMission(){const m=activeMission();if(!m)return;const note=document.getElementById('missionNote')?.value.trim()||'';const history=[{...m,note,completedAt:new Date().toISOString()},...missionHistory()].slice(0,12);saveJSON(HISTORY_KEY,history);localStorage.removeItem(MISSION_KEY);renderPractice();toast('Mission saved')}
function endMission(){localStorage.removeItem(MISSION_KEY);renderPractice();toast('Mission ended')}
function practiceButton(missionId,label='Start 5-round mission',source='Guide'){return `<button class="primary" data-mission="${esc(missionId)}" data-source="${esc(source)}">${esc(label)}</button>`}
function bindMissionButtons(){document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>startMissionById(b.dataset.mission,b.dataset.source||'Guide'));const dynamic=document.querySelector('[data-dynamic-mission]');if(dynamic)dynamic.onclick=()=>{const raw=JSON.parse(dynamic.dataset.dynamicMission);startMission(raw,dynamic.dataset.source||'Guide')}}
function dynamicMissionButton(m,source){return `<button class="primary" data-dynamic-mission='${esc(JSON.stringify(m))}' data-source="${esc(source)}">Start 5-round mission</button>`}
function renderProgressCard(){const p=progress(),total=LEARN.lessons.length,done=p.completed.filter(id=>lessonById(id)).length,next=LEARN.lessons.find(l=>!p.completed.includes(l.id)),last=lessonById(p.last),resume=last&&!p.completed.includes(last.id)?last:next;const pct=total?Math.round(done/total*100):0;return `<div class="progress-card"><div class="progress-head"><strong>Beginner lessons</strong><span>${done}/${total}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><small>${done===total?'All beginner lessons completed. Human progress has occurred.':resume?`Next: ${esc(resume.title)}`:'Choose a lesson to begin.'}</small>${resume?`<div class="quick-actions"><button class="secondary" data-go="lesson/${resume.id}">Continue learning</button></div>`:''}</div>`}
function renderMissionSnapshot(){const m=activeMission();if(!m)return `<div class="card"><h3>No active practice mission</h3><p>Choose one small behavior to test for five rounds. Attempting to repair an entire personality mid-match remains outside the app's warranty.</p><button class="secondary" data-go="practice">Choose a mission</button></div>`;return `<div class="mission-card"><span class="badge yellow">ACTIVE MISSION</span><h3>${esc(m.title)}</h3><p>${esc(m.instruction)}</p><div class="round-dots">${[0,1,2,3,4].map(i=>`<div class="round-dot ${m.results[i]==='yes'?'yes':m.results[i]==='no'?'no':''}">${m.results[i]==='yes'?'✓':m.results[i]==='no'?'×':i+1}</div>`).join('')}</div><button class="primary" data-go="practice">Open practice tracker</button></div>`}
function renderHome(){setNav('home');main.innerHTML=`<section class="hero"><span class="badge">BEGINNER GUIDE 3.3.1</span><h1>Learn Search &amp; Destroy without being thrown to the wolves.</h1><p>Use Guided Help to understand a round, complete the short beginner path, and practice one replacement action at a time.</p></section>${renderProgressCard()}${renderMissionSnapshot()}<div class="path"><button class="path-step" data-go="guided"><b>1</b><strong>Understand what went wrong</strong><small>Answer two or three questions and get one likely cause.</small></button><button class="path-step" data-go="learn"><b>2</b><strong>Learn the mode</strong><small>Work through the main rules, decisions, and game terms.</small></button><button class="path-step" data-go="practice"><b>3</b><strong>Practice one correction</strong><small>Track five rounds instead of trying to fix everything at once.</small></button></div><div class="section-label">Fast access</div><div class="button-list two"><button class="bigrow" data-go="guided/q/died-when"><strong>I was eliminated</strong><small>Start with when it happened.</small></button><button class="bigrow" data-go="quick/our-bomb-planted"><strong>We planted the bomb</strong><small>Use positions, sound, and the timer.</small></button><button class="bigrow" data-go="quick/enemy-bomb-planted"><strong>The enemy planted</strong><small>Check time, group, clear, and protect the defuse.</small></button><button class="bigrow" data-go="terms"><strong>I heard a term I do not know</strong><small>Open the game-term dictionary.</small></button></div>`;bindGo();window.scrollTo(0,0)}
function renderGuidedStart(){setNav('guided');const q=GUIDED.questions.start;main.innerHTML=`<section class="hero"><span class="badge">GUIDED ROUND REVIEW</span><h1>Turn a confusing round into one useful correction.</h1><p>No score judgment. No random teammate screaming. Just enough questions to identify the most likely problem.</p></section>${questionMarkup('start',q,1)}`;bindGuided();window.scrollTo(0,0)}
function questionMarkup(id,q,step){return `<section class="question-card"><div class="question-count">Step ${step}</div><h1>${esc(q.prompt)}</h1><p>${esc(q.help||'')}</p></section><div class="choice-grid">${q.options.map(o=>`<button class="choice" data-next="${esc(o.next||'')}" data-result="${esc(o.result||'')}"><strong>${esc(o.label)}</strong>${o.detail?`<small>${esc(o.detail)}</small>`:''}</button>`).join('')}</div>${q.back?`<div class="quick-actions"><button class="ghost" data-go="guided/q/${q.back}">← Previous question</button><button class="ghost" data-go="guided">Start over</button></div>`:''}`}
function guidedDepth(id){return id==='start'?1:['died-when','round-lost','our-plant','enemy-plant'].includes(id)?2:3}
function renderGuidedQuestion(id){const q=GUIDED.questions[id];if(!q)return go('guided');setNav('guided');main.innerHTML=`<button class="ghost" data-go="guided">← Guided start</button>${questionMarkup(id,q,guidedDepth(id))}`;bindGo();bindGuided();window.scrollTo(0,0)}
function bindGuided(){document.querySelectorAll('[data-next],[data-result]').forEach(b=>b.onclick=()=>{if(b.dataset.result)go(`guided/result/${b.dataset.result}`);else if(b.dataset.next)go(`guided/q/${b.dataset.next}`)})}
function renderGuidedResult(id){const r=GUIDED.results[id];if(!r)return go('guided');setNav('guided');const links=[r.lesson?`<button class="secondary" data-go="lesson/${r.lesson}">Open related lesson</button>`:'',r.fight?`<button class="secondary" data-go="fight/${r.fight}">Open fight correction</button>`:'',r.operation?`<button class="secondary" data-go="operation/${r.operation}">Open Field Manual operation</button>`:''].join('');main.innerHTML=`<button class="ghost" data-go="guided">← Start another review</button><section class="hero"><span class="badge">LIKELY EXPLANATION</span><h1>${esc(r.title)}</h1></section><div class="now"><strong>Try this next round</strong><span>${esc(r.action)}</span></div><div class="result-grid"><div class="result-box"><strong>What likely happened</strong>${esc(r.likely)}</div><div class="result-box"><strong>Why the correction helps</strong>${esc(r.why)}</div></div>${termNote(r.terms)}<div class="mission-card"><span class="badge yellow">PRACTICE IT</span><h3>${esc(missionById(r.mission)?.title||'Five-round mission')}</h3><p>${esc(missionById(r.mission)?.instruction||'Practice this correction for five rounds.')}</p><div class="quick-actions">${practiceButton(r.mission,'Start this mission','Guided diagnosis')}</div></div><div class="quick-actions">${links}${shareButton()}</div>`;bindGo();bindShare();bindMissionButtons();window.scrollTo(0,0)}
function renderQuickList(){setNav('guided');main.innerHTML=`<button class="ghost" data-go="guided">← Guided help</button><section class="hero"><span class="badge">DIRECT MID-MATCH HELP</span><h2>What is happening right now?</h2><p>Skip the diagnosis and open the closest situation.</p></section><div class="button-list">${LEARN.quick.map(q=>`<button class="bigrow" data-go="quick/${q.id}"><strong>${esc(q.title)}</strong><small>${esc(q.short)}</small></button>`).join('')}</div>`;bindGo();window.scrollTo(0,0)}
function renderQuick(id){const q=quickById(id);if(!q)return go('quick');setNav('guided');main.innerHTML=`<button class="ghost" data-go="quick">← All situations</button><section class="hero"><span class="badge">QUICK HELP</span><h1>${esc(q.title)}</h1><p>${esc(q.short)}</p></section><div class="now"><strong>Do this now</strong><span>${esc(q.action)}</span></div><div class="card"><h3>Four steps</h3><div class="steps">${q.steps.map(x=>`<div class="step">${esc(x)}</div>`).join('')}</div></div><div class="card"><h3>Why this works</h3><p>${esc(q.why)}</p></div>${termNote(q.terms)}<div class="quick-actions">${shareButton()}<button class="ghost" data-go="guided">Open guided review</button></div>`;bindGo();bindShare();window.scrollTo(0,0)}
function renderLearn(){setNav('learn');const p=progress();main.innerHTML=`<section class="hero"><span class="badge">LEARN THE MODE</span><h2>The parts nobody should have to discover through humiliation.</h2><p>Read in order or open the exact subject that keeps costing rounds.</p></section>${renderProgressCard()}<div class="button-list">${LEARN.lessons.map((l,i)=>`<button class="bigrow" data-go="lesson/${l.id}"><strong>${p.completed.includes(l.id)?'✓ ':''}${i+1}. ${esc(l.title)}</strong><small>${esc(l.subtitle)}</small></button>`).join('')}</div><div class="section-label">Individual fights</div><button class="bigrow" data-go="fights"><strong>Winning Fights</strong><small>Ten repeated fight problems with one correction and one practice mission.</small></button><div class="section-label">Deeper practice</div><button class="bigrow" data-go="manual"><strong>Open the 30-operation Field Manual</strong><small>Problem-based lessons for decisions, awareness, bomb play, and improvement.</small></button>`;bindGo();window.scrollTo(0,0)}
function renderLesson(id){const l=lessonById(id);if(!l)return go('learn');setLastLesson(id);const p=progress(),done=p.completed.includes(id);setNav('learn');main.innerHTML=`<button class="ghost" data-go="learn">← All lessons</button><section class="hero"><span class="badge">BEGINNER LESSON</span><h1>${esc(l.title)}</h1><p>${esc(l.subtitle)}</p></section><div class="lesson-status"><strong>${done?'<span class="check">✓ Completed</span>':'Not completed yet'}</strong><button class="${done?'ghost':'primary'}" id="lessonComplete">${done?'Mark incomplete':'Mark lesson complete'}</button></div><div class="now"><strong>Main idea</strong><span>${esc(l.takeaway)}</span></div>${l.sections.map(s=>`<section class="lesson-section"><h3>${esc(s[0])}</h3><p>${esc(s[1])}</p></section>`).join('')}<div class="card"><h3>Common mistakes</h3><ul class="mistakes">${l.mistakes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${termNote(l.terms)}<div class="quick-actions">${shareButton()}<button class="ghost" data-go="guided">Open guided help</button></div>`;document.getElementById('lessonComplete').onclick=()=>toggleLesson(id);bindGo();bindShare();window.scrollTo(0,0)}
function renderFights(){setNav('learn');main.innerHTML=`<button class="ghost" data-go="learn">← Learn</button><section class="hero"><span class="badge">WINNING FIGHTS</span><h2>Which repeated fight problem sounds familiar?</h2><p>The common game term is preserved and explained instead of being used as an entrance exam.</p></section><div class="button-list">${FIGHTS.map(f=>`<button class="bigrow" data-go="fight/${f.id}"><strong>${esc(f.trigger)}</strong><small>Game term: ${esc(f.term)} · ${esc(f.cue)}</small></button>`).join('')}</div>`;bindGo();window.scrollTo(0,0)}
function renderFight(id){const f=fightById(id);if(!f)return go('fights');setNav('learn');const dm={id:`fight-${f.id}`,title:f.title,short:f.cue,instruction:f.mission,cue:f.cue,route:`fight/${f.id}`};main.innerHTML=`<button class="ghost" data-go="fights">← Winning Fights</button><section class="hero"><span class="badge">FIGHT CORRECTION</span><h1>${esc(f.title)}</h1><p>${esc(f.summary)}</p></section><div class="now"><strong>Remember this during the round</strong><span>${esc(f.cue)}</span></div>${termNote([slug(f.term)])}<div class="compare"><div class="bad"><strong>What went wrong</strong>${esc(f.summary)}</div><div class="good"><strong>Better choice</strong>${esc(f.correction)}</div></div><div class="card"><h3>Four-step correction</h3><div class="steps">${f.steps.map(x=>`<div class="step">${esc(x)}</div>`).join('')}</div></div><div class="mission-card"><span class="badge yellow">FIVE-ROUND PRACTICE</span><h3>${esc(f.mission)}</h3><div class="quick-actions">${dynamicMissionButton(dm,'Winning Fights')}</div></div><div class="quick-actions">${shareButton()}<button class="ghost" data-go="manual">Related Field Manual</button></div>`;bindGo();bindShare();bindMissionButtons();window.scrollTo(0,0)}
function manualRow(o){return `<button class="bigrow" data-go="operation/${o.id}"><strong>${esc(o.title)}</strong><small>Operation ${String(o.id).padStart(2,'0')} · ${esc(o.mission)}</small></button>`}
function renderManual(){setNav('learn');main.innerHTML=`<button class="ghost" data-go="learn">← Learn</button><section class="hero"><span class="badge">FIELD MANUAL</span><h2>Thirty deeper problem-based lessons</h2><p>Use this when the same mistake keeps returning and a quick sentence is no longer enough.</p></section><input class="search" id="manualSearch" placeholder="Search dying early, bomb, timer, sound, cover..."><div class="manual-list" id="manualList">${MANUAL.operations.map(manualRow).join('')}</div>`;bindGo();document.getElementById('manualSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('manualList').innerHTML=MANUAL.operations.filter(o=>JSON.stringify(o).toLowerCase().includes(q)).map(manualRow).join('');bindGo()};window.scrollTo(0,0)}
function renderOperation(id){const o=MANUAL.operations.find(x=>x.id===Number(id));if(!o)return go('manual');setNav('learn');const text=[o.title,o.problem,o.truth,o.try,o.mission,o.success].join(' '),dm={id:`operation-${o.id}`,title:o.title,short:o.mission,instruction:o.mission,cue:o.try,route:`operation/${o.id}`};main.innerHTML=`<button class="ghost" data-go="manual">← Field Manual</button><section class="hero"><span class="badge">OPERATION ${String(o.id).padStart(2,'0')}</span><h1>${esc(o.title)}</h1></section><div class="now"><strong>One thing to try</strong><span>${esc(o.try)}</span></div><div class="card"><h3>The problem</h3><p>${esc(o.problem)}</p></div><div class="card"><h3>Why it happens</h3><p>${esc(o.truth)}</p></div><div class="mission-card"><span class="badge yellow">PRACTICE MISSION</span><h3>${esc(o.mission)}</h3><div class="quick-actions">${dynamicMissionButton(dm,'Field Manual')}</div></div><div class="card"><h3>Success looks like</h3><p>${esc(o.success)}</p></div>${termNote(termsInText(text))}<div class="quick-actions">${shareButton()}</div>`;bindGo();bindShare();bindMissionButtons();window.scrollTo(0,0)}
function renderPractice(){setNav('practice');const m=activeMission(),history=missionHistory();if(!m){main.innerHTML=`<section class="hero"><span class="badge">PRACTICE MISSIONS</span><h1>Fix one behavior for five rounds.</h1><p>Choose a mission, test it, record whether you remembered it, and keep one short note. Tiny controlled experiments: apparently learning can occur without public humiliation.</p></section><div class="section-label">Recommended missions</div><div class="button-list">${GUIDED.missions.slice(0,12).map(x=>`<button class="bigrow" data-mission="${x.id}" data-source="Practice list"><strong>${esc(x.title)}</strong><small>${esc(x.short)}</small></button>`).join('')}</div><div class="section-label">Field notes</div><button class="bigrow" data-go="notes"><strong>Open field notes</strong><small>Record one useful observation after a round or match.</small></button>${historyMarkup(history)}`;bindGo();bindMissionButtons();window.scrollTo(0,0);return}const completed=m.rounds>=5;main.innerHTML=`<section class="hero"><span class="badge">ACTIVE PRACTICE</span><h1>${esc(m.title)}</h1><p>${esc(m.source)} · ${m.rounds}/5 rounds recorded</p></section><div class="mission-card"><p>${esc(m.instruction)}</p>${m.cue?`<div class="mission-cue">${esc(m.cue)}</div>`:''}<div class="round-dots">${[0,1,2,3,4].map(i=>`<div class="round-dot ${m.results[i]==='yes'?'yes':m.results[i]==='no'?'no':''}">${m.results[i]==='yes'?'✓':m.results[i]==='no'?'×':i+1}</div>`).join('')}</div><div class="stat-grid"><div class="stat"><b>${m.rounds}</b><span>Rounds</span></div><div class="stat"><b>${m.successes}</b><span>Remembered</span></div><div class="stat"><b>${m.rounds-m.successes}</b><span>Missed</span></div></div>${completed?`<h3>Five rounds complete</h3><textarea class="notearea" id="missionNote" placeholder="One useful note: What changed? What stayed difficult?"></textarea><div class="quick-actions"><button class="primary" id="finishMission">Save and finish</button><button class="ghost" id="repeatMission">Repeat mission</button></div>`:`<div class="quick-actions"><button class="primary" id="missionYes">Remembered it</button><button class="ghost" id="missionNo">Missed it</button></div>`}<div class="quick-actions">${m.route?`<button class="secondary" data-go="${esc(m.route)}">Open related guide</button>`:''}<button class="ghost danger" id="endMission">End mission</button></div></div>${historyMarkup(history)}`;bindGo();if(!completed){document.getElementById('missionYes').onclick=()=>recordMission(true);document.getElementById('missionNo').onclick=()=>recordMission(false)}else{document.getElementById('finishMission').onclick=finishMission;document.getElementById('repeatMission').onclick=()=>{const again={...m,rounds:0,successes:0,results:[],startedAt:new Date().toISOString()};saveJSON(MISSION_KEY,again);renderPractice()}}document.getElementById('endMission').onclick=endMission;window.scrollTo(0,0)}
function historyMarkup(history){if(!history.length)return'';return `<div class="section-label">Recent practice</div><div class="history-list">${history.slice(0,5).map(h=>`<div class="history-row"><strong>${esc(h.title)} · ${h.successes}/5</strong><small>${esc(h.note||'No note saved.')}</small></div>`).join('')}</div>`}
function renderTerms(){setNav('terms');main.innerHTML=`<section class="hero"><span class="badge">GAME-TERM DICTIONARY</span><h2>Learn the language without already needing to know it.</h2><p>Established in-game and S&amp;D terminology stays. Disposable social-media slang does not get to charge admission.</p></section><input class="search" id="termSearch" placeholder="Search trade, re-peek, plant, rotation..."><div class="term-list" id="termList">${[...terms].sort((a,b)=>a.term.localeCompare(b.term)).map(termRow).join('')}</div>`;bindGo();document.getElementById('termSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById('termList').innerHTML=terms.filter(t=>(t.term+' '+t.definition).toLowerCase().includes(q)).map(termRow).join('');bindGo()};window.scrollTo(0,0)}
function termRow(t){return `<button class="term-row" data-go="term/${encodeURIComponent(t.id)}"><strong>${esc(t.term)}</strong><small>${esc(t.definition)}</small></button>`}
function renderTerm(id){const t=termById(id);if(!t)return go('terms');setNav('terms');main.innerHTML=`<button class="ghost" data-go="terms">← Dictionary</button><section class="hero"><span class="badge">GAME TERM</span><h1>${esc(t.term)}</h1><p>${esc(t.definition)}</p></section><div class="card accent"><h3>Why the dictionary exists</h3><p>The guide keeps real game terminology so players can understand teammates, videos, and competitive discussion. Every term should be learnable without already belonging to the club.</p></div><div class="quick-actions">${shareButton()}</div>`;bindGo();bindShare();window.scrollTo(0,0)}
function renderNotes(){setNav('practice');const saved=localStorage.getItem(NOTES_KEY)||'';main.innerHTML=`<button class="ghost" data-go="practice">← Practice</button><section class="hero"><span class="badge">FIELD NOTES</span><h2>Turn one mistake into one replacement action.</h2><p>Notes are stored only on this device.</p></section><textarea id="notes" class="notearea" placeholder="Example:\nI died crossing while sprinting. Next match I will stop at cover and pre-aim before crossing.\n\nNew term: trade = staying close enough to respond after a teammate is eliminated."></textarea><div class="quick-actions"><button class="primary" id="saveNotes">Save notes</button><button class="ghost" id="clearNotes">Clear</button></div><div class="card"><h3>Four useful review questions</h3><div class="steps"><div class="step">What did I know before moving?</div><div class="step">What directions could see me?</div><div class="step">What did the bomb and timer require?</div><div class="step">What one action will I change next round?</div></div></div>`;document.getElementById('notes').value=saved;document.getElementById('saveNotes').onclick=()=>{localStorage.setItem(NOTES_KEY,document.getElementById('notes').value);toast('Field notes saved')};document.getElementById('clearNotes').onclick=()=>{document.getElementById('notes').value='';localStorage.removeItem(NOTES_KEY);toast('Notes cleared')};bindGo();window.scrollTo(0,0)}
function renderAbout(){setNav('');main.innerHTML=`<button class="ghost" data-go="home">← Start</button><section class="hero"><span class="badge">VERSION 3.3.1</span><h1>A beginner-first Search &amp; Destroy companion</h1><p>Created by Michael Barnes to help players learn the mode without depending on trial, error, and abuse from strangers.</p></section><div class="card"><h3>What changed in 3.3</h3><p>Guided round diagnosis, lesson completion tracking, continue-learning progress, five-round practice missions, practice history, and direct mission links from fight corrections and Field Manual operations.</p></div><div class="card"><h3>Language rule</h3><p>Use ordinary language first. Keep established game terminology, define it in the dictionary, and point readers toward that definition when it appears.</p></div><div class="card"><h3>Privacy</h3><p>Lesson progress, practice results, history, and field notes remain on this device. Nothing is submitted automatically.</p></div><div class="card"><h3>Build</h3><p>Version 3.3.1 · MB-SNDC-2026-0723-034</p><p>Copyright © 2026 Michael Barnes. All Rights Reserved.</p></div>`;bindGo();window.scrollTo(0,0)}
function render(){const parts=route().split('/'),root=parts[0],a=parts[1],b=parts[2];if(root==='home')renderHome();else if(root==='guided'&&!a)renderGuidedStart();else if(root==='guided'&&a==='q')renderGuidedQuestion(b||'start');else if(root==='guided'&&a==='result')renderGuidedResult(b);else if(root==='quick'&&!a)renderQuickList();else if(root==='quick')renderQuick(a);else if(root==='learn')renderLearn();else if(root==='lesson')renderLesson(a);else if(root==='fights')renderFights();else if(root==='fight')renderFight(a);else if(root==='manual')renderManual();else if(root==='operation')renderOperation(a);else if(root==='practice')renderPractice();else if(root==='terms')renderTerms();else if(root==='term')renderTerm(a);else if(root==='notes')renderNotes();else if(root==='about')renderAbout();else go('home')}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.root));document.getElementById('aboutBtn').onclick=()=>go('about');window.addEventListener('hashchange',render);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;const b=document.getElementById('installBtn');b.hidden=false;b.onclick=async()=>{await deferredInstall.prompt();deferredInstall=null;b.hidden=true}});
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{const reg=await navigator.serviceWorker.register('./sw.js');const updateBtn=document.getElementById('updateBtn');const offer=w=>{waitingWorker=w;updateBtn.hidden=false;updateBtn.onclick=()=>waitingWorker.postMessage({type:'SKIP_WAITING'})};if(reg.waiting)offer(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)offer(w)})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())})}
if(!location.hash)location.hash='#/home';else render();
